### ISSUE TITLE
App crashes when starting

### ISSUE THREAD

**Issue by rodrigosalinas** [Thinkmill/touchstone-starter#6]
Hi. I did everything the instructions said. I donwload the project, I ran `npm install` inside the project (that was not mentioned but I assumed it was necessary), then I ran `gulp dev`. This happened (with or without `sudo`):
````
iMac-de-Rodrigo:touchstone-starter-master rodrigosalinas$ sudo gulp dev
[20:49:55] Using gulpfile ~/proyectos/touchstone-starter-master/gulpfile.js
[20:49:55] Starting 'html'...
[20:49:55] Starting 'images'...
[20:49:55] Starting 'fonts'...
[20:49:55] Starting 'less'...
[20:49:55] Starting 'watch-scripts'...
[20:49:55] Starting 'serve'...
[20:49:56] Finished 'serve' after 99 ms
Local Server ready on port 8000
/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/index.js:68
    }).done(undefined, cb);
       ^
TypeError: undefined is not a function
    at DestroyableTransform._transform (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/index.js:68:8)
    at DestroyableTransform.Transform._read (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_transform.js:172:12)
    at doWrite (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at DestroyableTransform.Writable.write (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/touchstonejs-tasks/node_modules/gulp-less/node_modules/through2/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:632:7)
    at DestroyableTransform.pipeOnReadable (/Users/rodrigosalinas/proyectos/touchstone-starter-master/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:664:5)
    at DestroyableTransform.emit (events.js:104:17)
iMac-de-Rodrigo:touchstone-starter-master rodrigosalinas$ 
```
Can you help me please? I really want to use your framework and I don't want to wait for the docs. Thanks a lot for your work.

**Comment by rodrigosalinas** [comment]
It was a `gulp-less` issue. I updated `gulp-less` inside `touchstonejs-tasks` to version 3.0.1 and everything worked just fine. Thanks anyway.
